import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navbar from '~/components/layout/Navbar';
import SearchInput from '~/components/SearchInput';

const nunito = Nunito({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'gitfinder.',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${nunito.className} h-screen flex flex-col bg-blue-950 md:w-[55%] w-full mx-auto`}
      >
        <Navbar />

        <main className='flex-grow flex flex-col gap-2 p-4'>
          <SearchInput />
          {children}
        </main>
      </body>
    </html>
  );
}
